name: Subsription Automation Workflow

on:
  workflow_dispatch:
    inputs:
      values:
        description: "input"
        required: true
        type: string
        default: ""
      

jobs:
  #Test Job
  trigger_external_workflow1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo and Sleep 
        uses: actions/checkout@v3
        run: |
              echo "Inside Echo and Sleep"
              echo "Input Value : ${{github.event.inputs.values}}
              sleep 20
              exit 0
