name: Subsription Automation Workflow

on:
  workflow_dispatch:
    inputs:
      values:
        description: "input"
        required: true
        type: string
        default: ""
      id:
        description: "random id"
        required: false
        type: string
        default: ""


jobs:

  #Test Job
  trigger_external_workflow1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
              echo "Inside Echo and Sleep"
              echo "Input Value : ${{github.event.inputs.values}}"
      - name: Sleep
        run: sleep 60
      - name: Test
        run: |
              echo "Inside Test"
              echo "Bye"

  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
