name: Subsription Automation Workflow

on:
  workflow_dispatch:
    inputs:
      subscription-ids:
        description: "subscription-ids"
        required: true
        type: string
        default: ""
      run-apply:
        description: "Apply terraform to subscription.  Uncheck to run plan only."
        required: true
        type: boolean
        default: true
      #subscription-id:
      #  description: "subscription-id"
      #  required: true
      #  type: string
      #  default: ""
      ms-id:
        description: "ms-id"
        required: true
        type: string
        default: ""
      environment:
        description: "environment"
        required: true
        type: string
        default: ""
      tag-to-deploy:
        description: "tag-to-deploy"
        required: false
        type: string
        default: ""

jobs:

  #Workflow Trigger for Step 13 -  Apply custom role to Prod
  trigger_external_workflow:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Apply PIM to Prod Customers
        uses: actions/checkout@v3
        with:
          workflow: 'Apply PIM to Prod Customers'
          repo: 'optum-labs/Apollo.PIM.Customer/.github/workflows/apply-pim-prod.yml @main'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'
          secrets: inherit
          #subscription-ids: [${{github.event.inputs.subscription-ids}}]
          workflow-version: main
        env:
          CONDITION: ${{ github.event.head_commit.message }}

 
